var test = require('tape')
var esp = require('../../index.js')

test('returns all the correct methods', function (t) {
  t.plan(36)

  var sdk = esp()

  t.ok(sdk.getDashboard, 'getDashboard method present')
  t.ok(sdk.getAlerts, 'getAlerts method present')
  t.ok(sdk.getAlert, 'getAlert method present')
  t.ok(sdk.getCloudTrailEvents, 'getCloudTrailEvents method present')
  t.ok(sdk.getCloudTrailEvent, 'getCloudTrailEvent method present')
  t.ok(sdk.getCustomSignatures, 'getCustomSignatures method present')
  t.ok(sdk.getCustomSignature, 'getCustomSignature method present')
  t.ok(sdk.getExternalAccounts, 'getExternalAccounts method present')
  t.ok(sdk.getExternalAccount, 'getExternalAccount method present')
  t.ok(sdk.getOrganizations, 'getOrganizations method present')
  t.ok(sdk.getOrganization, 'getOrganization method present')
  t.ok(sdk.getRegions, 'getRegions method present')
  t.ok(sdk.getRegion, 'getRegion method present')
  t.ok(sdk.getReports, 'getReports method present')
  t.ok(sdk.getReport, 'getReport method present')
  t.ok(sdk.getServices, 'getServices method present')
  t.ok(sdk.getService, 'getService method present')
  t.ok(sdk.getSignatures, 'getSignatures method present')
  t.ok(sdk.getSignature, 'getSignature method present')
  t.ok(sdk.getStatsForReportLatest, 'getStatsForReportLatest method present')
  t.ok(sdk.getStatsForReport, 'getStatsForReport method present')
  t.ok(sdk.getStatsForRegion, 'getStatsForRegion method present')
  t.ok(sdk.getStatsForService, 'getStatsForService method present')
  t.ok(sdk.getStatsForSignature, 'getStatsForSignature method present')
  t.ok(sdk.getStatsForCustomSignature, 'getStatsForCustomSignature method present')
  t.ok(sdk.getSuborganizations, 'getSuborganizations method present')
  t.ok(sdk.getSuborganization, 'getSuborganization method present')
  t.ok(sdk.getSuppressions, 'getSuppressions method present')
  t.ok(sdk.getSuppressions, 'getSuppressions method present')
  t.ok(sdk.getSuppression, 'getSuppression method present')
  t.ok(sdk.getTagsForAlert, 'getTagsForAlert method present')
  t.ok(sdk.getTag, 'getTag method present')
  t.ok(sdk.getTeams, 'getTeams method present')
  t.ok(sdk.getTeam, 'getTeam method present')
  t.ok(sdk.getUsers, 'getUsers method present')
  t.ok(sdk.getUser, 'getUser method present')
})
